import "./globals.css";
import Providers from "./providers";
import { Toaster } from "react-hot-toast";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Cristopher | Front-End Developer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="dark:bg-dark_bg">
        <Providers>
          <Toaster position="top-center" />

          {children}
        </Providers>
      </body>
    </html>
  );
}
